# Generated by Django 2.1.12 on 2019-11-12 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('Classification_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=50)),
                ('Abbrev', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('Email_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('File_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Filename', models.CharField(max_length=50)),
                ('Size', models.IntegerField()),
                ('Classification', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('Network_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Classifications', models.ManyToManyField(to='pages.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('Request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DateCreated', models.DateTimeField()),
                ('DatePulled', models.DateTimeField()),
                ('DateOneEye', models.DateTimeField()),
                ('DateTwoEye', models.DateTimeField()),
                ('DateComplete', models.DateTimeField()),
                ('DiscNumber', models.IntegerField()),
                ('IsSubmitted', models.BooleanField()),
                ('PullNumber', models.IntegerField()),
                ('Emails', models.ManyToManyField(to='pages.Email')),
                ('Network', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Network')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Email')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.User'),
        ),
    ]
