# Generated by Django 2.1.12 on 2019-11-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191113_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='classification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Classification'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='network',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Network'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Email'),
        ),
    ]
