# Generated by Django 2.1.12 on 2019-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('pages', '0006_auto_20191121_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='Classifications',
        ),
        migrations.AddField(
            model_name='network',
            name='classifications',
            field=models.ManyToManyField(to='pages.Classification'),
        ),
#        migrations.AddField(
#            model_name='request',
#            name='files',
#            field=models.ManyToManyField(to='pages.File'),
#        ),
    ]
