# Generated by Django 2.1.12 on 2019-11-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191121_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rejection_reason',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Rejection'),
        ),
    ]
