# Generated by Django 2.1.12 on 2019-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191121_1222'),
    ]

    operations = [
#        migrations.RenameField(
#            model_name='request',
#            old_name='Emails',
#            new_name='target_emails',
#        ),
#        migrations.AddField(
#            model_name='request',
#            name='files',
#            field=models.ManyToManyField(to='pages.File'),
#        ),
    ]
