# Generated by Django 2.1.12 on 2019-11-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191121_1223'),
    ]

    operations = [
#        migrations.RenameField(
#            model_name='request',
#            old_name='Emails',
#            new_name='target_emails',
#        ),
        migrations.RemoveField(
            model_name='request',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='file',
            name='rejection_reason',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Rejection'),
        ),
        migrations.AddField(
            model_name='file',
            name='rejection_text',
            field=models.TextField(blank=True, default=None),
        ),
#        migrations.AddField(
#            model_name='request',
#            name='files',
#            field=models.ManyToManyField(to='pages.File'),
#        ),
    ]
