# Generated by Django 2.1.12 on 2020-01-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200114_0848'),
        ('pages', '0013_auto_20200114_0953'),
    ]

    operations = [
    ]
