# Generated by Django 2.1.12 on 2020-02-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200114_1002'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='request',
#            name='target_emails',
#        ),
#        migrations.AddField(
#            model_name='request',
#            name='target_email',
#            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Email'),
#            preserve_default=False,
#        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Email'),
        ),
    ]
