# Generated by Django 2.1.12 on 2020-02-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20200213_1643'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='request',
#            name='target_email',
#            field=models.CharField(blank=True, max_length=100, null=True),
#        ),
    ]
