# Generated by Django 2.1.12 on 2020-02-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20200213_1645'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='request',
#            name='target_email',
#            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Email'),
#        ),
    ]
