# Generated by Django 2.1.12 on 2020-02-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20200213_1654'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='request',
#            name='target_email',
#        ),
    ]
