# Generated by Django 2.1.12 on 2020-02-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_request_target_email'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='request',
#            name='target_emails',
#        ),
        migrations.AddField(
            model_name='request',
            name='target_email',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Email'),
        ),
    ]
