# Generated by Django 2.1.12 on 2020-02-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20200213_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='target_emails',
        ),
    ]
