# Generated by Django 2.1.12 on 2020-02-13 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_remove_request_target_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='target_email',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Email'),
        ),
    ]
