# Generated by Django 2.1.12 on 2020-02-25 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0025_auto_20200213_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user_complete',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_complete', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='user_oneeye',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_oneeye', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='user_pulled',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_pulled', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='user_twoeye',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_twoeye', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
