# Generated by Django 2.1.12 on 2020-04-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20200331_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='rejection_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
