# Generated by Django 2.1.12 on 2020-04-02 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0030_auto_20200401_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('pull_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pull_number', models.IntegerField(blank=True, null=True)),
                ('date_pulled', models.DateTimeField(blank=True, null=True)),
                ('date_oneeye', models.DateTimeField(blank=True, null=True)),
                ('date_twoeye', models.DateTimeField(blank=True, null=True)),
                ('date_complete', models.DateTimeField(blank=True, null=True)),
                ('disc_number', models.IntegerField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Network')),
            ],
            options={
                'ordering': ['-date_pulled'],
            },
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['file_object']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name_last']},
        ),
        migrations.RemoveField(
            model_name='request',
            name='date_complete',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date_oneeye',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date_pulled',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date_twoeye',
        ),
        migrations.RemoveField(
            model_name='request',
            name='disc_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='pull_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user_complete',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user_oneeye',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user_pulled',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user_twoeye',
        ),
        migrations.AddField(
            model_name='pull',
            name='user_complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_complete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pull',
            name='user_oneeye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_oneeye', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pull',
            name='user_pulled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_pulled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pull',
            name='user_twoeye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_user_twoeye', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='pull',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Pull'),
        ),
    ]
