# Generated by Django 2.1.12 on 2020-04-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20200402_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pull',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Pull'),
        ),
    ]
