# Generated by Django 2.1.12 on 2020-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20200402_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejection',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
