# Generated by Django 2.1.12 on 2020-04-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_rejection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='files',
            field=models.ManyToManyField(limit_choices_to={'rejection_reason': None}, to='pages.File'),
        ),
    ]
