# Generated by Django 2.1.12 on 2020-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20200420_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='files',
            field=models.ManyToManyField(to='pages.File'),
        ),
    ]
