# Generated by Django 2.1.12 on 2020-04-24 19:18

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_user_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_object',
            field=models.FileField(max_length=500, upload_to=pages.models.randomize_path),
        ),
    ]
