# Generated by Django 2.1.12 on 2020-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20200424_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_pii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='to_encrypt',
            field=models.BooleanField(default=False),
        ),
    ]
