# Generated by Django 2.1.12 on 2020-04-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20200424_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='to_encrypt',
            new_name='is_centcom_info',
        ),
    ]
