# Generated by Django 2.1.12 on 2020-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20200424_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
