# Generated by Django 2.1.12 on 2020-10-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_resourcelink_file_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelink',
            name='url_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
