# Generated by Django 2.1.12 on 2020-10-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_auto_20201009_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelink',
            name='url_path',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
