# Generated by Django 2.1.12 on 2020-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_auto_20201009_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelink',
            name='file_object',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
