# Generated by Django 2.1.12 on 2020-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_auto_20201009_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='target_email',
        ),
        migrations.AddField(
            model_name='request',
            name='target_email',
            field=models.ManyToManyField(default=None, null=True, to='pages.Email'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='file_object',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
