# Generated by Django 2.1.12 on 2020-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_auto_20201023_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='target_email',
            field=models.ManyToManyField(to='pages.Email'),
        ),
    ]
