# Generated by Django 2.1.12 on 2021-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_auto_20201023_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_centcom',
            field=models.BooleanField(default=False),
        ),
    ]
