# Generated by Django 2.1.12 on 2021-05-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_auto_20210510_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='centcom_pull',
            field=models.BooleanField(default=False),
        ),
    ]
