# Generated by Django 2.1.12 on 2021-05-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_request_centcom_pull'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='centcom_pull',
            field=models.BooleanField(default=False),
        ),
    ]
