# Generated by Django 2.1.12 on 2021-06-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_pull_centcom_pull'),
        ('pages', '0052_user_phone'),
    ]

    operations = [
    ]
