# Generated by Django 2.1.12 on 2021-06-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_merge_20210617_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='is_centcom_info',
            new_name='is_centcom',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='centcom_pull',
            new_name='is_centcom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_centcom',
        ),
    ]
