# Generated by Django 2.1.12 on 2021-07-20 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_auto_20210623_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirtyWord',
            fields=[
                ('dirtyword_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('case_sensitive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
