# Generated by Django 2.1.12 on 2021-07-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_user_user_identifier'),
        ('pages', '0057_dirtyword'),
    ]

    operations = [
    ]
