# Generated by Django 2.1.12 on 2021-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_merge_20210722_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
