# Generated by Django 2.1.12 on 2021-08-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_request_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_rejected',
        ),
    ]
