# Generated by Django 3.2.6 on 2021-09-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_remove_request_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_pulled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
