# Generated by Django 2.1.12 on 2021-09-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0061_request_date_pulled'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_dupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='request_hash',
            field=models.CharField(default='', max_length=255),
        ),
    ]
