# Generated by Django 2.1.12 on 2021-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0062_auto_20210914_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['file_name']},
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
