# Generated by Django 2.1.12 on 2021-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
