# Generated by Django 2.1.12 on 2021-09-28 15:14

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_auto_20210924_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('file_name'), nulls_last=True)]},
        ),
        migrations.AddField(
            model_name='file',
            name='NDCI',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
