# Generated by Django 2.1.12 on 2021-09-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_feedback_category'),
        ('pages', '0064_network_visible'),
    ]

    operations = [
    ]
