# Generated by Django 2.1.12 on 2021-09-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_auto_20210924_1223'),
        ('pages', '0064_auto_20210928_1114'),
        ('pages', '0065_merge_20210928_1123'),
        ('pages', '0066_auto_20210924_1150'),
        ('pages', '0063_auto_20210924_0902'),
    ]

    operations = [
    ]
