# Generated by Django 2.1.12 on 2021-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0067_merge_20210928_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='has_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
