# Generated by Django 2.1.12 on 2021-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0068_request_has_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='all_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
