# Generated by Django 2.1.12 on 2021-10-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0068_request_destflag'),
        ('pages', '0069_request_all_rejected'),
    ]

    operations = [
    ]
