# Generated by Django 3.2.8 on 2021-10-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0070_merge_20211014_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
