# Generated by Django 3.2.8 on 2021-10-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0071_auto_20211015_0815'),
        ('pages', '0071_user_banned'),
    ]

    operations = [
    ]
