# Generated by Django 3.2.8 on 2021-10-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0072_merge_0071_auto_20211015_0815_0071_user_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
    ]
