# Generated by Django 3.2.8 on 2021-11-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0073_auto_20211026_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='network',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.network'),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='emails',
            field=models.ManyToManyField(to='pages.Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_email', to='pages.email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_identifier',
            field=models.CharField(default='00000.0000.0.0000000', max_length=150),
        ),
    ]
