# Generated by Django 3.2.8 on 2021-11-09 11:46

from django.db import migrations

def migrateEmails(apps, schema_editor):
    Network = apps.get_model("pages", "Network")
    User = apps.get_model("pages", "User")
    Email = apps.get_model("pages", "Email")
    db_alias = schema_editor.connection.alias

    for user in User.objects.using(db_alias).all():
        SIPR = Network.objects.using(db_alias).get(name="SIPR")

        oldEmail = Email.objects.using(db_alias).get(email_id=user.email.email_id)
        oldEmail.network=SIPR
        oldEmail.save()
        
        user.emails.add(oldEmail)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0074_auto_20211109_0644'),
    ]

    operations = [
        migrations.RunPython(migrateEmails)
    ]
