# Generated by Django 3.2.8 on 2021-11-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0075_auto_20211109_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
