# Generated by Django 3.2.8 on 2021-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0077_user_update_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_identifier',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
