# Generated by Django 3.2.8 on 2021-11-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0082_remove_file_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['completed', '-date_submitted']},
        ),
    ]
