# Generated by Django 3.2.8 on 2021-11-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0083_alter_feedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_org',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
