# Generated by Django 3.2.8 on 2021-12-07 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0083_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
