# Generated by Django 3.2.8 on 2021-12-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0084_auto_20211130_0854'),
        ('pages', '0084_auto_20211207_0652'),
    ]

    operations = [
    ]
