# Generated by Django 3.2.9 on 2021-12-16 12:33

from django.db import migrations, models
import pages.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0085_merge_0084_auto_20211130_0854_0084_auto_20211207_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_object',
            field=models.FileField(max_length=500, storage=pages.models.CustomFileSystemStorage(), upload_to=pages.models.randomize_path_file),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
