# Generated by Django 3.2.8 on 2021-12-09 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pages.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0085_merge_0084_auto_20211130_0854_0084_auto_20211207_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_oneeye',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_twoeye',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='user_oneeye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_user_oneeye', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='user_twoeye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_user_twoeye', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='ready_to_pull',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classification',
            name='classification_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_object',
            field=models.FileField(max_length=500, storage=pages.models.CustomFileSystemStorage(), upload_to=pages.models.randomize_path),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
