# Generated by Django 3.2.8 on 2021-12-09 14:04

from django.db import migrations

def migrateOldRequests(apps, schema_editor):
    Requests = apps.get_model("pages", "Request")
    db_alias = schema_editor.connection.alias

    for request in Requests.objects.using(db_alias).all():
        if request.pull != None:
            pull = request.pull
            for file in request.files.all():
                file.user_oneeye = pull.user_oneeye
                file.date_oneeye = pull.date_oneeye
                file.user_twoeye = pull.user_twoeye
                file.date_twoeye = pull.date_twoeye
                file.save()

            if pull.user_oneeye != None and pull.user_twoeye != None:
                request.ready_to_pull = True
                request.save()

def backItUp(apps, schema_editor):
    Requests = apps.get_model("pages", "Request")
    db_alias = schema_editor.connection.alias

    for request in Requests.objects.using(db_alias).all():
        if request.pull != None:
            pull = request.pull
            for file in request.files.all():
                file.user_oneeye = None
                file.date_oneeye = None
                file.user_twoeye = None
                file.date_twoeye = None
                file.save()

            if pull.user_oneeye != None and pull.user_twoeye != None:
                request.ready_to_pull = False
                request.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0086_auto_20211209_0904'),
    ]

    operations = [
        migrations.RunPython(migrateOldRequests, backItUp)
    ]
