# Generated by Django 3.2.8 on 2021-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0089_file_scan_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='files_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
