# Generated by Django 3.2.8 on 2022-01-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0086_auto_20211216_0733'),
        ('pages', '0091_request_rejected_dupe'),
    ]

    operations = [
    ]
