# Generated by Django 3.2.11 on 2022-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0092_merge_20220107_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_policy',
            field=models.BooleanField(default=False),
        ),
    ]
