# Generated by Django 3.2.11 on 2022-02-03 14:54

from django.db import migrations
from pages.views.dev_tools import resetUpdateInfo, reverseFunction

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0093_user_read_policy'),
    ]

    operations = [
        migrations.RunPython(resetUpdateInfo, reverseFunction)
    ]
