# Generated by Django 3.2.11 on 2022-02-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0093_resourcelink_policy'),
        ('pages', '0093_user_read_policy'),
        ('pages', '0093_user_temp_ban_count'),
    ]

    operations = [
    ]
