# Generated by Django 4.0.2 on 2022-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0094_merge_20220210_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='has_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
