# Generated by Django 4.0.3 on 2022-03-22 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0094_merge_20220210_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('visible', models.BooleanField(default=False)),
                ('color', models.CharField(choices=[('danger', 'red'), ('warning', 'yellow'), ('success', 'green'), ('info', 'blue')], default='warning', max_length=20)),
            ],
        ),
    ]
