# Generated by Django 4.0.2 on 2022-03-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0095_message'),
        ('pages', '0095_request_rhr_email'),
    ]

    operations = [
    ]
