# Generated by Django 4.0.3 on 2022-03-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0095_message'),
        ('pages', '0095_request_rhr_email'),
    ]

    operations = [
    ]
