# Generated by Django 4.0.2 on 2022-03-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0097_drop_file_request_has_encrypted_drop_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop_request',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
