# Generated by Django 4.0.3 on 2022-06-23 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0099_alter_feedback_user_alter_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='CFTS_deployed',
            new_name='cfts_deployed',
        ),
        migrations.AddField(
            model_name='network',
            name='skip_file_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='destination_emails',
            field=models.ManyToManyField(blank=True, to='pages.email'),
        ),
    ]
