# Generated by Django 4.0.3 on 2022-06-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0100_rename_cfts_deployed_network_cfts_deployed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop_request',
            name='has_encrypted',
        ),
    ]
