# Generated by Django 4.0.3 on 2022-06-23 15:53

from django.db import migrations
from django.db.models import Q

def userCleanup(apps, schema_editor):
    User = apps.get_model("pages", "User")
    authUser = apps.get_model("auth", "User")

    db_alias = schema_editor.connection.alias

    delUsers = User.objects.using(db_alias).filter(Q(user_identifier=None) | Q(user_identifier="") | Q(
        user_identifier="2ab155e3a751644ee4073972fc4534be158aa0891e8a8df6cd1631f56c61f06073d288fed905d0932fde78155c83208deb661361e64eb1a0f3d736ed04a7e4dc"))
    delUsers.delete()

    delAuthUsers = authUser.objects.using(db_alias).filter(is_staff=False)
    delAuthUsers.delete()

def reverseFunction(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0101_remove_drop_request_has_encrypted'),
    ]

    operations = [
        migrations.RunPython(userCleanup, reverseFunction)
    ]
