# Generated by Django 4.0.3 on 2022-07-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0104_remove_pull_centcom_pull_remove_pull_date_oneeye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='rejection_reasons',
            field=models.ManyToManyField(blank=True, related_name='file_rejection_reasons', to='pages.rejection'),
        ),
        migrations.AlterField(
            model_name='file',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_rejection_reason', to='pages.rejection'),
        ),
    ]
