# Generated by Django 4.0.3 on 2022-08-16 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0107_remove_file_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategories',
            fields=[
                ('file_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_category', models.CharField(max_length=35, null=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='file_categories',
            field=models.ManyToManyField(to='pages.filecategories'),
        ),
    ]
