# Generated by Django 5.2 on 2025-05-14 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0108_filecategories_request_file_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceBannerSettings',
            fields=[
                ('compliance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compliance_text', models.TextField(null=True)),
                ('visible', models.BooleanField(default=False)),
                ('accept_button_text', models.CharField(default='Accept', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceBannerAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accepted', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.user')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.compliancebannersettings')),
            ],
            options={
                'unique_together': {('user', 'banner')},
            },
        ),
    ]
