# Generated by Django 5.2 on 2025-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0110_alter_compliancebanneracceptance_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliancebanneracceptance',
            old_name='last_accepted',
            new_name='accepted_at',
        ),
        migrations.AddField(
            model_name='compliancebannersettings',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancebannersettings',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
