# Generated by Django 5.1.2 on 2025-05-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0111_rename_last_accepted_compliancebanneracceptance_accepted_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancebanneracceptance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.user"
            ),
        ),
    ]
